import { Link } from 'react-router';
import Footer from '../components/Footer';

function Section({ title, children }) {
  return (
    <section className="mt-10">
      <h2 className="text-lg font-semibold text-charcoal">{title}</h2>
      <div className="mt-3 space-y-3 text-sm leading-7 text-charcoal-400">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-canvas">
      <div className="mx-auto w-full max-w-3xl flex-1 px-6 py-12">
        <div className="flex items-center justify-between">
          <p className="text-sm font-medium uppercase tracking-[0.18em] text-teal-700">StructureMyLearning</p>
          <Link className="text-sm text-charcoal-400 hover:text-charcoal" to="/">← Back</Link>
        </div>

        <h1 className="mt-8 text-3xl font-semibold tracking-tight text-charcoal">Terms of Service</h1>
        <p className="mt-2 text-sm text-charcoal-400">Last updated: May 2026</p>

        <Section title="Acceptance of Terms">
          <p>By creating an account or using StructureMyLearning, you agree to these Terms of Service. If you do not agree, please do not use the service.</p>
        </Section>

        <Section title="Account Registration">
          <p>You must provide accurate information when creating an account. You are responsible for keeping your credentials secure and for all activity that occurs under your account.</p>
        </Section>

        <Section title="Acceptable Use">
          <p>You agree not to use StructureMyLearning to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Scrape, crawl, or systematically extract content from the service</li>
            <li>Attempt to reverse-engineer, probe, or compromise our systems</li>
            <li>Submit prompts designed to generate harmful, illegal, or abusive content</li>
            <li>Impersonate another person or entity</li>
          </ul>
        </Section>

        <Section title="AI-Generated Content">
          <p>Learning guides and topic content on StructureMyLearning are generated by AI models. This content is provided for <strong className="text-charcoal">educational and informational purposes only</strong>. It is not professional advice (legal, medical, financial, or otherwise) and may contain inaccuracies.</p>
          <p>We do not guarantee the accuracy, completeness, or fitness for a particular purpose of any AI-generated content. Always verify important information from authoritative sources.</p>
        </Section>

        <Section title="Intellectual Property">
          <p>The prompts and learning goals you submit remain yours. The AI-generated content produced in response is provided to you for personal, non-commercial use.</p>
          <p>The StructureMyLearning name, logo, and interface are our intellectual property and may not be reproduced without permission.</p>
        </Section>

        <Section title="Service Availability">
          <p>We provide the service on an as-available basis and do not guarantee uninterrupted access. We may modify, suspend, or discontinue features at any time, with or without notice.</p>
        </Section>

        <Section title="Termination">
          <p>We reserve the right to suspend or terminate accounts that violate these terms or that engage in behaviour that harms other users or the service.</p>
        </Section>

        <Section title="Limitation of Liability">
          <p>To the fullest extent permitted by law, StructureMyLearning is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
        </Section>

        <Section title="Changes to Terms">
          <p>We may update these terms from time to time. Continued use of the service after changes are posted constitutes your acceptance of the updated terms.</p>
        </Section>

        <Section title="Contact">
          <p>Questions about these terms? <Link className="text-teal-700 hover:underline" to="/contact">Contact us</Link>.</p>
        </Section>
      </div>

      <Footer className="border-t border-charcoal/10" />
    </div>
  );
}
